# Generated by Django 3.0.3 on 2020-05-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20200515_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coins',
            field=models.TextField(blank=True),
        ),
    ]
