# Generated by Django 3.0.3 on 2020-05-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_user_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='send_daily_prices',
            field=models.BooleanField(default=False),
        ),
    ]
